### ISSUE TITLE
Check if it works with "Release" builds 

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/ReactNative-HelloWorld#4]
@mattiasmak reports that React Native apps work great in "Debug" builds of React Native, but not with "Release" builds.

@alshakero can you pls check if "Release" build of `ReactNative-HelloWorld` works as intended, as the first thing after your vacation?

@mattiasmak pls provide more details if needed.

**Comment by alshakero** [comment]
@warpech to give you some relief, I emailed @mattiasmak back about meeting @11:00 am today if that suits him. Or any time if not.

**Comment by mattiasmak** [comment]
We solved it. Stupid of us to use a web api only available when debugging. `Performance.now()`
Easy once we found it, but hard to find. Thanks Omar!

**Comment by warpech** [comment]
Stupid of React Native to not warn about it. 

I am so happy it turned out to be so trivial.

Thanks guys!
